# Generated by Django 5.2.15 on 2026-06-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_servicebooking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'site visit',
                'verbose_name_plural': 'site visits',
                'ordering': ['-created_at'],
            },
        ),
    ]
