# Generated by Django 5.2.15 on 2026-06-25 11:21

import django.core.validators
import shop.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, default='', help_text='Upload a product video (MP4/MOV/WebM). Stored on Cloudinary when configured.', storage=shop.storage.select_video_storage, upload_to='product_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm', 'ogg', 'm4v'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Optional: external video link (used only if no file is uploaded above).', max_length=500),
        ),
    ]
